Repository Stoobly/stoobly-agent, pull requests merged in 2024-04, with the labels that each got.

#213 OAS Import Command for Stoobly CLI #212
  stoobly_agent/app/cli/endpoint_cli.py
  stoobly_agent/app/cli/helpers/endpoint_facade.py
  stoobly_agent/app/cli/helpers/endpoints_import_context.py
  stoobly_agent/app/cli/helpers/endpoints_import_service.py
  stoobly_agent/app/cli/helpers/openapi_endpoint_adapter.py
  stoobly_agent/app/models/types/endpoint.py
  stoobly_agent/lib/api/api.py
  stoobly_agent/lib/api/body_param_names_resource.py
  stoobly_agent/lib/api/endpoints_resource.py
  stoobly_agent/lib/api/header_names_resource.py
  stoobly_agent/lib/api/interfaces/endpoints.py
  stoobly_agent/lib/api/query_param_names_resource.py
  stoobly_agent/lib/api/response_header_names_resource.py
  stoobly_agent/lib/api/response_param_names_resource.py
  stoobly_agent/test/app/cli/helpers/openapi_endpoint_adapter_additional_props_test.py
  stoobly_agent/test/app/cli/helpers/openapi_endpoint_adapter_missing_info_test.py
  stoobly_agent/test/app/cli/helpers/openapi_endpoint_adapter_missing_oauth2_scopes_test.py
  stoobly_agent/test/app/cli/helpers/openapi_endpoint_adapter_missing_servers_test.py
  stoobly_agent/test/app/cli/helpers/openapi_endpoint_adapter_test.py
Labels: enhancement, priority/longterm

#221 Add mode.REPLAY to allowed modes to set
  stoobly_agent/app/settings/intercept_settings.py
Labels: bug

#222 217 endpoint import formatting
  stoobly_agent/app/cli/endpoint_cli.py
  stoobly_agent/app/cli/helpers/endpoints_import_service.py
Labels: enhancement
